# Generated by Django 5.0.6 on 2024-06-05 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoWeb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_name', models.CharField(max_length=100)),
                ('Question_level', models.IntegerField(default=0)),
                ('Question_Course', models.IntegerField(default=0)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('Add_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicalQuestionInfo', models.TextField(max_length=100)),
                ('practicalQuestionAnswers', models.TextField(max_length=100)),
                ('practicalQuestionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legoWeb.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChoiceQuestionInfo', models.TextField(max_length=100)),
                ('choiceQst_Op1', models.TextField(max_length=100)),
                ('choiceQst_Op2', models.TextField(max_length=100)),
                ('choiceQst_Op3', models.TextField(max_length=100)),
                ('choiceQst_Op4', models.TextField(max_length=100)),
                ('choiceQst_answer', models.CharField(max_length=100)),
                ('ChoiceQuestionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legoWeb.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='TrueOrFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionInfo', models.TextField(max_length=100)),
                ('questionAnswers', models.CharField(max_length=100)),
                ('questionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legoWeb.questiontype')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
